title: "Amy J. Davis"
author: "Amy J. Davis"
description: ":)"
permalink: /:title/
remote_theme: pages-themes/architect@v0.2.0
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:amyjdavis@users.noreply.github.com"}
  - {title: Github, icon: github, url: "https://github.com/amyjdavis"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/theamyjdavis"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-remote-theme # add this line to the plugins list if you already have one
